name: BWCosmetics
version: '${project.version}'
main: me.alen_alex.bwcosmetics.BWCosmetics
authors:
  - Alen_Alex
  - Inferno
depend:
  - BedWars1058
softdepend:
  - Citizens
commands:
  bwc:
    description: Test
  bwc2:
    description: Test2